version: '3.8'
services:
  app:
    container_name: jira-app
    image: jira-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - SPRING_DATASOURCE_USERNAME=jira
      - SPRING_DATASOURCE_PASSWORD=JiraRush

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
      - POSTGRES_DB=jira

  db-test:
    container_name: db-test
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
      - POSTGRES_DB=jira

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf